[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
tokio = { version = "1.44.1", features = ["fs"] }
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
